#!/usr/bin/env python3
"""Extract key sections from a documentation plan for JIRA description.

Supports both JTBD and feature-based plan formats.

Usage: python3 extract-description.py <plan_file> <output_file> <public|private>
"""
import re
import sys
from datetime import date


def extract(plan_content: str, is_public: bool) -> str:
    keep_headings = [
        # JTBD plan headings
        "## What is the main JTBD",
        "## How does the JTBD",
        # Feature-based plan headings
        "## What are the primary user stories",
        "## How do these features relate",
        # Common to both
        "## Who can provide information",
    ]

    sections = []
    for heading in keep_headings:
        pattern = rf"({re.escape(heading)}[^\n]*\n)(.*?)(?=\n## |\Z)"
        match = re.search(pattern, plan_content, re.DOTALL)
        if match:
            sections.append(match.group(0).strip())

    description = "\n\n".join(sections)

    today = date.today().strftime("%Y-%m-%d")
    if is_public:
        footer = (
            f"\n\n----\n"
            f"(i) Doc requirements generated by Claude {today}.\n"
            f"*Review and validate AI generated doc plans for accuracy "
            f"with an SME before implementation.*"
        )
    else:
        footer = (
            f"\n\n----\n"
            f"(i) Doc requirements generated by Claude {today}.\n"
            f"See the attached markdown file for the preliminary generated "
            f"doc plans and proposed updated docs topics.\n"
            f"*Review and validate AI generated doc plans for accuracy "
            f"with an SME before implementation.*"
        )

    return description + footer


if __name__ == "__main__":
    if len(sys.argv) != 4:
        print(
            f"Usage: {sys.argv[0]} <plan_file> <output_file> <public|private>",
            file=sys.stderr,
        )
        sys.exit(1)

    plan_file, output_file, visibility = sys.argv[1], sys.argv[2], sys.argv[3]

    with open(plan_file, encoding="utf-8") as f:
        content = f.read()

    result = extract(content, is_public=(visibility == "public"))

    with open(output_file, "w", encoding="utf-8") as f:
        f.write(result)
